AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: !Ref NODE_ENV
        AWS_REGION: !Ref AWS::Region
        SECRET_NAME: cms_secrets  # AWS Secrets Manager Name

Parameters:
  NODE_ENV:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: "Set the environment (development, staging, production)"

Resources:
  NodeAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "cms-app-${NODE_ENV}"
      Handler: app.lambdaHandler  # Update if needed
      Runtime: nodejs18.x
      CodeUri: .
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:cms_secrets-*"
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          NODE_ENV: !Ref NODE_ENV
          SECRET_NAME: cms_secrets
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/post/get
            Method: get

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${NODE_ENV}/api/v1/post/get"
