AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref EnvironmentType  # Renamed to avoid linting issues
        SECRET_NAME: cms_secrets  # AWS Secrets Manager Name

Parameters:
  EnvironmentType:
    Type: String
    Default: development
    AllowedValues:
      - development
      - staging
      - production
    Description: "Set the environment (development, staging, production)"

Resources:
  NodeAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "cms-app-${EnvironmentType}"
      PackageType: Image  # Use Image instead of Zip
      ImageUri: 711387116482.dkr.ecr.ap-south-1.amazonaws.com/custom_cms_backend:latest  # Use your ECR image URI
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:cms_secrets-*"
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvironmentType  # Updated environment variable name
          SECRET_NAME: cms_secrets
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/post/get
            Method: get

Outputs:
  ApiGatewayInvokeURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentType}/api/v1/post/get"
